components/Balance.tsx
=> Format balance from formatted attribute

components/Header.tsx, components/Holdings.tsx, components/Transactions.tsx, lib/config.ts, lib/moralis.ts, lib/web3uath.ts, pages/_app.tsx, pages/api/transactions/[chain]/[address].ts, pages/index.tsx
- Magic button to switch chain
- Autoconnect (with annoying popup)
=> Multichain support

components/Actions.tsx
=> add buy glo modal with info

lib/utils.ts, lib/web3uath.ts, package-lock.json
- Dynamic network based on vercel env
=> Dynamic network setup

components/Balance.tsx
=> Show yield as a range starting at 0

components/CTA.tsx, index.d.ts, package-lock.json
=> Open ctas in new tab

components/Header.tsx
Resolves #9 
Context: https://github.com/Glo-Foundation/glo-wallet/issues/9#issuecomment-1573423901
I think `less = more` in this case unless I'm missing something 😬
=> Stay connected on refresh without auto-popupping Sequence

pages/_app.tsx
Mounted condition on app level
=> Hydration fix

components/CTA.tsx, styles/globals.css
=> Nitpicking style for the "Let's Glo" section

components/Transactions.tsx, lib/auth.ts, lib/sequence-connector.ts, lib/utils.ts, package-lock.json, package.json, pages/_app.tsx, pages/index.tsx
- Custom sequnce connector
- Local storage (to be replaced with cookies)
=> Sequence server side verif

components/Transactions.tsx
=> Show sent to and received from wallet addresses in UI

components/Actions.tsx, package-lock.json
Design nitpick for the scan button :-)
I don't get why package-lock.json had to be changed so much :/
=> Don't show the Scan button at all when connected with Metamask / WC

components/Modals/UserAuthModal.tsx, pages/_app.tsx, styles/globals.css
Reverts Glo-Foundation/glo-wallet#74
=> Revert "Connect with light theme and banner"

components/Actions.tsx, components/Modals/BuyGloModal.tsx, components/Transactions.tsx
=> Buy some Glo CTA when someone has no Glo tx yet

components/Modals/UserAuthModal.tsx
Some code repetition necessary to make it work, afaict I can't inject the signInWithEmail preference into the existing sequence connector unfortunately. Seems to work though!
PS: I messed up some git stuff making the main branch dirty, sorry 😓
=> Sign in / up with email deeplink into sequence

components/Actions.tsx, next.config.js, pages/_app.tsx, pages/index.tsx
- deep links
- router rewrites
- clean router path so clean url is preserved
localhost:3000/buy
localhost:3000/sign-in
=> Deep links: buy & sign-in

components/CTA.tsx
=> CTAs headlines on 1 line

components/Actions.tsx, components/Modals/UserAuthModal.tsx, components/Transactions.tsx, pages/_app.tsx, styles/globals.css
=> Fix styling and usability issues

components/Modals/UserInfoModal.tsx, pages/index.tsx
- connect to default chain
extras:
- added chain name/id
- fix sign-in logic (with showedLogin)
=> Automatically suggest connecting to default chain

components/Header.tsx, components/Modals/BuyGloModal.tsx, components/Modals/UserAuthModal.tsx, components/Transactions.tsx, lib/context.ts, pages/_app.tsx, pages/index.tsx, styles/globals.css
@Syncretik trying a different approach real quick - seems promising?
=> Jeff head floats

components/AnimatedCheckIcon.tsx, components/CTA.tsx, index.d.ts, lib/spreadsheet.ts, package-lock.json, package.json, pages/api/ctas.ts, pages/api/eas.ts, pages/api/sign-in.ts, preinstall.sh, public/check.svg, vercel.json
https://github.com/Glo-Foundation/glo-wallet/assets/6277878/0c9ad0ef-3af7-478c-ae27-03174cf53481
=> Validate that users completed the "Let's Glo" actions

components/Header.tsx, components/Transactions.tsx, pages/index.tsx
I don't think we need it, and it's causing Jeff's head to get chopped off on iOS safari
=> rm max-h-[100vh] everywhere

components/CTA.tsx, components/Modals/TweetModal.tsx, pages/oauth2/twitter.tsx
- msg expanded
- err feedback -> retry suggestion
- icon + name
=> Tweet Modal update - err handling, msg expanded

pages/api/market-cap.ts, utils.ts
- Market cap api (using mainnet data only for both envs)
=> Expose market api

components/CTA.tsx, lib/spreadsheet.ts, pages/api/sign-in.ts
- On sign up fetch referrals info from spreadsheet
- Fix Tweet msg to 0 decimals
=> Share glo with friends

lib/config.ts, middleware.ts, pages/_app.tsx
- middleware extended from api to all reuqests
- list all countries to compare with headers
=> Geofence prohibited countries for legal compliance

components/Modals/UserAuthModal.tsx, package-lock.json, package.json
- tos added - https://glodollar.org/tos ? 
- seq link added
- clsx added for clean classNames ifology
fixes #135 
fixes #109
=> Tos and sequence

components/Actions.tsx, components/Holdings.tsx, styles/globals.css
=> fix/transactions and input UI

components/Modals/BuyGloModal.tsx, components/Modals/UserAuthModal.tsx
- scroll to TOS
- reduce margins
=> Improve auth modal

components/Modals/BuyGloModal.tsx
=> Don't show Uniswap explanatory steps when authenticated with metamask/walletconnect

README.md
=> add style guidelines

components/Transactions.tsx
=> Open transactions dropdown by default;

components/Modals/UserInfoModal.tsx
=> Display email for seq wallet

next.config.js, pages/api/market-cap.ts, utils.ts
- add nice formatting X.YK or XXX.Y M etc (till market cap in trilions)
- cors unblocked for market cap api
=> Cors market api

components/Modals/BuyGloModal.tsx
=> Round yield down to 0 dollar when actual yield < 1 dollar

components/Modals/BuyingGuideModal.tsx
=> functional buy guide w/ auto-checks

components/CTA.tsx, pages/index.tsx
=> Adjust tweet

components/CTA.tsx, index.d.ts, lib/utils.ts, pages/api/sign-in.ts
=> Disable share glo

components/Modals/AllTransactionsModal.tsx, components/Transactions.tsx
=> affix transaction list length

components/Modals/PaymentOptionModal.tsx
- contnet adjusted
- icons fixed
vs logged users:
closes #201
=> Hide payment options for non-logged users

components/Modals/BuyingGuideModal.tsx
fixes #204  
fixes #213 
fixes #211
=> smoke testing feedback: round 1

components/Modals/BuyingGuideModal.tsx, utils.ts
=> USDC balance

components/CTA.tsx, components/Modals/AllTransactionsModal.tsx, components/Transactions.tsx
updated with new fixes
resolves #211
resolves #213
=> smoke testing round 1 additional fixes

lib/utils.ts
=> Adjust CTA default order

components/Modals/BuyingGuideModal.tsx
=> show non-sequence wallet copy variation for step #3 in buying guide

components/GloAnimated.tsx, components/ImpactInset.tsx, package-lock.json, package.json, public/glo-animation.json
=> Glo animated "coin"

components/Modals/BuyingGuideModal.tsx, components/Modals/PaymentOptionModal.tsx, payments.ts
resolves #207 
resolves #202
resolves #205
=> buy glo guide multi-provider support

components/Modals/BuyingGuideModal.tsx, pages/index.tsx
Alchemy seems not working with that anyway.
Public is displaying errors too.
Imho we will add balance refetch on some callbacks after Glo purchases lster on.
=> Remove watch: true

components/Modals/BuyGloModal.tsx, components/Modals/BuyingGuideModal.tsx, components/Modals/PaymentOptionModal.tsx
=> Dynamic buy amount in guide

components/CompletedIcon.tsx, components/Modals/BuyingGuideModal.tsx, components/Modals/PaymentOptionModal.tsx, components/Modals/TweetModal.tsx
=> Rad small fixes

components/Modals/TransactionDetailsModal.tsx, components/Modals/UserAuthModal.tsx, components/TransactionsList.tsx, styles/globals.css
=> Small redesign of login modal

components/GloAnimated.tsx
=> fix safari & mobile render issue of impact bar

components/Modals/UserInfoModal.tsx
=> Add a switch to polygon button if user on another network

components/DetailedEnoughToBuy.tsx, components/Holdings.tsx, components/Modals/BuyGloModal.tsx, pages/impact/[address].tsx
1. Make slider handle larger
2. Fix $0 yield handling in address impact page
3. Add link to bootstrapping article
=> Fix more ux changes

components/Actions.tsx, lib/store.ts, styles/globals.css
=> link xfers success toast to polygonscan

components/Modals/BuyingGuideModal.tsx
=> Add button to step by step guide to buyingguidemodal

pages/impact/[address].tsx
=> Fix impact balance sum

components/Transactions.tsx
- hide "Show All Transactions" <li> on init
- force close on login to prevent race condition when fetching and calculating transaction list height.
resolves #293
=> recalculate txns list length + hide errant li on init

prisma/migrations/20230803091208_remove_email_constraint/migration.sql, prisma/schema.prisma
Reverts Glo-Foundation/glo-wallet#316
=> Revert "Remove email constraint"

prisma/migrations/20230803093653_remove_real_email_constraint/migration.sql, prisma/schema.prisma
Test with:
```
SELECT
tablename,
indexname,
indexdef
FROM
pg_indexes
WHERE
schemaname = 'public';
```
=> Remove real email constraint

pages/_app.tsx
=> modal click overlay to close

components/Modals/BuyingGuideModal.tsx
=> Fix ratio conditional

payments.ts
Actually using different param fixes the edit mode too.
=> Transak: Default crypto amount

pages/impact/[address].tsx, tests/impact-calculations/impact.gui.ts
Integration Tests:
1. display example address's impact as per balance
2. simulate lifting ppl out of poverty by holding $123456 Glo
=> [e2e] simulate buying different amt Glo

lib/config.ts, pages/api/market-cap.ts, utils.ts
Not really visible there as Celo is at 1$.
=> Celo market cap

components/CTA.tsx, styles/globals.css, tests/ctas/ctas.gui.ts
=> Testing: help grow ctas

components/Balance.tsx, components/Holdings.tsx, components/ImpactInset.tsx, components/Modals/BuyGloModal.tsx, components/Modals/PaymentOptionModal.tsx, components/Transactions.tsx, pages/impact/[address].tsx, pages/index.tsx, utils.ts
=> Total balance as default buy amount

lib/config.ts, pages/impact/[address].tsx
resolves https://github.com/Glo-Foundation/glo-wallet/issues/362
=> add glo holdings breakdown to impact page

pages/index.tsx
=> Remove transfer calls

components/Modals/PaymentOptionModal.tsx
https://glodollar.slack.com/archives/C04PNCYTT89/p1693320596883569?thread_ts=1693243069.970209&cid=C04PNCYTT89
=> Fix Jeff error

lib/spreadsheet.ts
=> Read supporters tab emails

components/Balance.tsx, components/Modals/BuyWithCoinbaseSequenceModal.tsx, components/Modals/PaymentOptionModal.tsx
Sequence:
Swapable redirects to Sequence steps:
=> Add more steps to glo buy guide

components/Modals/PaymentOptionModal.tsx
=> Change payment options

components/Balance.tsx, components/Header.tsx, components/Home.tsx, components/ImpactInset.tsx, components/Modals/BoxBuyModal.tsx, components/Modals/BuyGloModal.tsx, components/Modals/BuyWithCoinbaseSequenceModal.tsx, components/Modals/SwapGate.tsx, components/Modals/SwapModal.tsx, next.config.js, pages/purchased.tsx, payments.ts, utils.ts
=> Coinbase fixes
